#!/usr/bin/env bash
set -e

(
  cd dev/dart/protoc
  docker build -t xmtp-dart/protoc .
)

mkdir -p dart/lib/src

# Generate the API using the dart:grpc plugin.
docker run --rm -i -v${PWD}:/code xmtp-dart/protoc \
  -I=./proto \
  --dart_out=grpc:dart/lib/src \
  message_api/v1/message_api.proto

# Generate the types using the dart plugin.
docker run --rm -i -v${PWD}:/code xmtp-dart/protoc \
  -I=./proto \
  --experimental_allow_proto3_optional \
  --dart_out=dart/lib/src \
  keystore_api/v1/keystore.proto \
  message_api/v1/authn.proto \
  message_contents/composite.proto \
  message_contents/signature.proto \
  message_contents/conversation_reference.proto \
  message_contents/ciphertext.proto \
  message_contents/public_key.proto \
  message_contents/contact.proto \
  message_contents/invitation.proto \
  message_contents/private_key.proto \
  message_contents/message.proto \
  message_contents/content.proto \
  message_contents/private_preferences.proto \
  message_contents/signed_payload.proto \
  message_contents/ecies.proto
