#!/usr/bin/env bash
set -e

# This shuffles files around to adhere to dart publishing conventions.
# See https://dart.dev/tools/pub/publishing#preparing-to-publish

# Get to the repo root
cd "$(dirname "$0")"
cd ../../

cp ./README.md ./dart/README.md
cp ./LICENSE ./dart/LICENSE
# TODO: include changelog if/when we have one
#cp ./CHANGELOG.md ./dart/CHANGELOG.md

# Update pubspec.yaml version to use tagged version
# See https://dart.dev/tools/pub/automated-publishing#triggering-automated-publishing-from-github-actions
sed -i "s/version: 0.0.0/version: $RELEASE_VERSION/" ./dart/pubspec.yaml
