//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_api/v1/message_api.proto

package org.xmtp.proto.message.api.v1;

@kotlin.jvm.JvmName("-initializequeryRequest")
public inline fun queryRequest(block: org.xmtp.proto.message.api.v1.QueryRequestKt.Dsl.() -> kotlin.Unit): org.xmtp.proto.message.api.v1.MessageApiOuterClass.QueryRequest =
  org.xmtp.proto.message.api.v1.QueryRequestKt.Dsl._create(org.xmtp.proto.message.api.v1.MessageApiOuterClass.QueryRequest.newBuilder()).apply { block() }._build()
public object QueryRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: org.xmtp.proto.message.api.v1.MessageApiOuterClass.QueryRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: org.xmtp.proto.message.api.v1.MessageApiOuterClass.QueryRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): org.xmtp.proto.message.api.v1.MessageApiOuterClass.QueryRequest = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ContentTopicsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated string content_topics = 1;</code>
     * @return A list containing the contentTopics.
     */
    public val contentTopics: com.google.protobuf.kotlin.DslList<kotlin.String, ContentTopicsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getContentTopicsList()
      )
    /**
     * <code>repeated string content_topics = 1;</code>
     * @param value The contentTopics to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addContentTopics")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ContentTopicsProxy>.add(value: kotlin.String) {
      _builder.addContentTopics(value)
    }
    /**
     * <code>repeated string content_topics = 1;</code>
     * @param value The contentTopics to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignContentTopics")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ContentTopicsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <code>repeated string content_topics = 1;</code>
     * @param values The contentTopics to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllContentTopics")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ContentTopicsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllContentTopics(values)
    }
    /**
     * <code>repeated string content_topics = 1;</code>
     * @param values The contentTopics to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllContentTopics")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ContentTopicsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <code>repeated string content_topics = 1;</code>
     * @param index The index to set the value at.
     * @param value The contentTopics to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setContentTopics")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ContentTopicsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setContentTopics(index, value)
    }/**
     * <code>repeated string content_topics = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearContentTopics")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ContentTopicsProxy>.clear() {
      _builder.clearContentTopics()
    }
    /**
     * <code>uint64 start_time_ns = 2;</code>
     */
    public var startTimeNs: kotlin.Long
      @JvmName("getStartTimeNs")
      get() = _builder.getStartTimeNs()
      @JvmName("setStartTimeNs")
      set(value) {
        _builder.setStartTimeNs(value)
      }
    /**
     * <code>uint64 start_time_ns = 2;</code>
     */
    public fun clearStartTimeNs() {
      _builder.clearStartTimeNs()
    }

    /**
     * <code>uint64 end_time_ns = 3;</code>
     */
    public var endTimeNs: kotlin.Long
      @JvmName("getEndTimeNs")
      get() = _builder.getEndTimeNs()
      @JvmName("setEndTimeNs")
      set(value) {
        _builder.setEndTimeNs(value)
      }
    /**
     * <code>uint64 end_time_ns = 3;</code>
     */
    public fun clearEndTimeNs() {
      _builder.clearEndTimeNs()
    }

    /**
     * <code>.xmtp.message_api.v1.PagingInfo paging_info = 4;</code>
     */
    public var pagingInfo: org.xmtp.proto.message.api.v1.MessageApiOuterClass.PagingInfo
      @JvmName("getPagingInfo")
      get() = _builder.getPagingInfo()
      @JvmName("setPagingInfo")
      set(value) {
        _builder.setPagingInfo(value)
      }
    /**
     * <code>.xmtp.message_api.v1.PagingInfo paging_info = 4;</code>
     */
    public fun clearPagingInfo() {
      _builder.clearPagingInfo()
    }
    /**
     * <code>.xmtp.message_api.v1.PagingInfo paging_info = 4;</code>
     * @return Whether the pagingInfo field is set.
     */
    public fun hasPagingInfo(): kotlin.Boolean {
      return _builder.hasPagingInfo()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun org.xmtp.proto.message.api.v1.MessageApiOuterClass.QueryRequest.copy(block: org.xmtp.proto.message.api.v1.QueryRequestKt.Dsl.() -> kotlin.Unit): org.xmtp.proto.message.api.v1.MessageApiOuterClass.QueryRequest =
  org.xmtp.proto.message.api.v1.QueryRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val org.xmtp.proto.message.api.v1.MessageApiOuterClass.QueryRequestOrBuilder.pagingInfoOrNull: org.xmtp.proto.message.api.v1.MessageApiOuterClass.PagingInfo?
  get() = if (hasPagingInfo()) getPagingInfo() else null

