// Structure for representing send key grants and revocations.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: message_contents/send_key.proto

package message_contents

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Wrapper for send key grants. There may be additional metadata in the
// future, for example the app/device this was granted for
type SendKeyGrant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Union:
	//
	//	*SendKeyGrant_V1_
	Union isSendKeyGrant_Union `protobuf_oneof:"union"`
}

func (x *SendKeyGrant) Reset() {
	*x = SendKeyGrant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_contents_send_key_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendKeyGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendKeyGrant) ProtoMessage() {}

func (x *SendKeyGrant) ProtoReflect() protoreflect.Message {
	mi := &file_message_contents_send_key_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendKeyGrant.ProtoReflect.Descriptor instead.
func (*SendKeyGrant) Descriptor() ([]byte, []int) {
	return file_message_contents_send_key_proto_rawDescGZIP(), []int{0}
}

func (m *SendKeyGrant) GetUnion() isSendKeyGrant_Union {
	if m != nil {
		return m.Union
	}
	return nil
}

func (x *SendKeyGrant) GetV1() *SendKeyGrant_V1 {
	if x, ok := x.GetUnion().(*SendKeyGrant_V1_); ok {
		return x.V1
	}
	return nil
}

type isSendKeyGrant_Union interface {
	isSendKeyGrant_Union()
}

type SendKeyGrant_V1_ struct {
	V1 *SendKeyGrant_V1 `protobuf:"bytes,1,opt,name=v1,proto3,oneof"`
}

func (*SendKeyGrant_V1_) isSendKeyGrant_Union() {}

// Wrapper for send key revocations. There may be additional metadata in
// the future, for example the app/device that performed the revocation
type SendKeyRevocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Union:
	//
	//	*SendKeyRevocation_V1_
	Union isSendKeyRevocation_Union `protobuf_oneof:"union"`
}

func (x *SendKeyRevocation) Reset() {
	*x = SendKeyRevocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_contents_send_key_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendKeyRevocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendKeyRevocation) ProtoMessage() {}

func (x *SendKeyRevocation) ProtoReflect() protoreflect.Message {
	mi := &file_message_contents_send_key_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendKeyRevocation.ProtoReflect.Descriptor instead.
func (*SendKeyRevocation) Descriptor() ([]byte, []int) {
	return file_message_contents_send_key_proto_rawDescGZIP(), []int{1}
}

func (m *SendKeyRevocation) GetUnion() isSendKeyRevocation_Union {
	if m != nil {
		return m.Union
	}
	return nil
}

func (x *SendKeyRevocation) GetV1() *SendKeyRevocation_V1 {
	if x, ok := x.GetUnion().(*SendKeyRevocation_V1_); ok {
		return x.V1
	}
	return nil
}

type isSendKeyRevocation_Union interface {
	isSendKeyRevocation_Union()
}

type SendKeyRevocation_V1_ struct {
	V1 *SendKeyRevocation_V1 `protobuf:"bytes,1,opt,name=v1,proto3,oneof"`
}

func (*SendKeyRevocation_V1_) isSendKeyRevocation_Union() {}

// V1
type SendKeyGrant_V1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyBundle *SignedPublicKeyBundleV2 `protobuf:"bytes,1,opt,name=key_bundle,json=keyBundle,proto3" json:"key_bundle,omitempty"`
}

func (x *SendKeyGrant_V1) Reset() {
	*x = SendKeyGrant_V1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_contents_send_key_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendKeyGrant_V1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendKeyGrant_V1) ProtoMessage() {}

func (x *SendKeyGrant_V1) ProtoReflect() protoreflect.Message {
	mi := &file_message_contents_send_key_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendKeyGrant_V1.ProtoReflect.Descriptor instead.
func (*SendKeyGrant_V1) Descriptor() ([]byte, []int) {
	return file_message_contents_send_key_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SendKeyGrant_V1) GetKeyBundle() *SignedPublicKeyBundleV2 {
	if x != nil {
		return x.KeyBundle
	}
	return nil
}

// V1
type SendKeyRevocation_V1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountRevokedPublicKey *AccountRevokedPublicKey `protobuf:"bytes,1,opt,name=account_revoked_public_key,json=accountRevokedPublicKey,proto3" json:"account_revoked_public_key,omitempty"`
}

func (x *SendKeyRevocation_V1) Reset() {
	*x = SendKeyRevocation_V1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_contents_send_key_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendKeyRevocation_V1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendKeyRevocation_V1) ProtoMessage() {}

func (x *SendKeyRevocation_V1) ProtoReflect() protoreflect.Message {
	mi := &file_message_contents_send_key_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendKeyRevocation_V1.ProtoReflect.Descriptor instead.
func (*SendKeyRevocation_V1) Descriptor() ([]byte, []int) {
	return file_message_contents_send_key_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SendKeyRevocation_V1) GetAccountRevokedPublicKey() *AccountRevokedPublicKey {
	if x != nil {
		return x.AccountRevokedPublicKey
	}
	return nil
}

var File_message_contents_send_key_proto protoreflect.FileDescriptor

var file_message_contents_send_key_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x73, 0x2f, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x6b, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x15, 0x78, 0x6d, 0x74, 0x70, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x21, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x5f, 0x6b, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa6, 0x01, 0x0a, 0x0c,
	0x53, 0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x02,
	0x76, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x78, 0x6d, 0x74, 0x70, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x56, 0x31,
	0x48, 0x00, 0x52, 0x02, 0x76, 0x31, 0x1a, 0x53, 0x0a, 0x02, 0x56, 0x31, 0x12, 0x4d, 0x0a, 0x0a,
	0x6b, 0x65, 0x79, 0x5f, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2e, 0x2e, 0x78, 0x6d, 0x74, 0x70, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x56, 0x32,
	0x52, 0x09, 0x6b, 0x65, 0x79, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x75,
	0x6e, 0x69, 0x6f, 0x6e, 0x22, 0xce, 0x01, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x02, 0x76, 0x31,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x78, 0x6d, 0x74, 0x70, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x56, 0x31, 0x48, 0x00, 0x52, 0x02, 0x76, 0x31, 0x1a, 0x71, 0x0a, 0x02, 0x56, 0x31, 0x12,
	0x6b, 0x0a, 0x1a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x76, 0x6f, 0x6b,
	0x65, 0x64, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x78, 0x6d, 0x74, 0x70, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x52, 0x17, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x76, 0x6f,
	0x6b, 0x65, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x42, 0x07, 0x0a, 0x05,
	0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x42, 0x4f, 0x0a, 0x1f, 0x6f, 0x72, 0x67, 0x2e, 0x78, 0x6d, 0x74,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x6d, 0x74, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x76, 0x33, 0x2f, 0x67, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_contents_send_key_proto_rawDescOnce sync.Once
	file_message_contents_send_key_proto_rawDescData = file_message_contents_send_key_proto_rawDesc
)

func file_message_contents_send_key_proto_rawDescGZIP() []byte {
	file_message_contents_send_key_proto_rawDescOnce.Do(func() {
		file_message_contents_send_key_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_contents_send_key_proto_rawDescData)
	})
	return file_message_contents_send_key_proto_rawDescData
}

var file_message_contents_send_key_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_message_contents_send_key_proto_goTypes = []interface{}{
	(*SendKeyGrant)(nil),            // 0: xmtp.message_contents.SendKeyGrant
	(*SendKeyRevocation)(nil),       // 1: xmtp.message_contents.SendKeyRevocation
	(*SendKeyGrant_V1)(nil),         // 2: xmtp.message_contents.SendKeyGrant.V1
	(*SendKeyRevocation_V1)(nil),    // 3: xmtp.message_contents.SendKeyRevocation.V1
	(*SignedPublicKeyBundleV2)(nil), // 4: xmtp.message_contents.SignedPublicKeyBundleV2
	(*AccountRevokedPublicKey)(nil), // 5: xmtp.message_contents.AccountRevokedPublicKey
}
var file_message_contents_send_key_proto_depIdxs = []int32{
	2, // 0: xmtp.message_contents.SendKeyGrant.v1:type_name -> xmtp.message_contents.SendKeyGrant.V1
	3, // 1: xmtp.message_contents.SendKeyRevocation.v1:type_name -> xmtp.message_contents.SendKeyRevocation.V1
	4, // 2: xmtp.message_contents.SendKeyGrant.V1.key_bundle:type_name -> xmtp.message_contents.SignedPublicKeyBundleV2
	5, // 3: xmtp.message_contents.SendKeyRevocation.V1.account_revoked_public_key:type_name -> xmtp.message_contents.AccountRevokedPublicKey
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_message_contents_send_key_proto_init() }
func file_message_contents_send_key_proto_init() {
	if File_message_contents_send_key_proto != nil {
		return
	}
	file_message_contents_public_key_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_message_contents_send_key_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendKeyGrant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_contents_send_key_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendKeyRevocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_contents_send_key_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendKeyGrant_V1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_contents_send_key_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendKeyRevocation_V1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_contents_send_key_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SendKeyGrant_V1_)(nil),
	}
	file_message_contents_send_key_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*SendKeyRevocation_V1_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_contents_send_key_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_contents_send_key_proto_goTypes,
		DependencyIndexes: file_message_contents_send_key_proto_depIdxs,
		MessageInfos:      file_message_contents_send_key_proto_msgTypes,
	}.Build()
	File_message_contents_send_key_proto = out.File
	file_message_contents_send_key_proto_rawDesc = nil
	file_message_contents_send_key_proto_goTypes = nil
	file_message_contents_send_key_proto_depIdxs = nil
}
