// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_contents/composite.proto

package org.xmtp.proto.message.contents;

public final class CompositeOuterClass {
  private CompositeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CompositeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:xmtp.message_contents.Composite)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
     */
    java.util.List<org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part> 
        getPartsList();
    /**
     * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
     */
    org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part getParts(int index);
    /**
     * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
     */
    int getPartsCount();
    /**
     * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
     */
    java.util.List<? extends org.xmtp.proto.message.contents.CompositeOuterClass.Composite.PartOrBuilder> 
        getPartsOrBuilderList();
    /**
     * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
     */
    org.xmtp.proto.message.contents.CompositeOuterClass.Composite.PartOrBuilder getPartsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * Composite is used to implement xmtp.org/composite content type
   * </pre>
   *
   * Protobuf type {@code xmtp.message_contents.Composite}
   */
  public static final class Composite extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:xmtp.message_contents.Composite)
      CompositeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Composite.newBuilder() to construct.
    private Composite(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Composite() {
      parts_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Composite();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.xmtp.proto.message.contents.CompositeOuterClass.internal_static_xmtp_message_contents_Composite_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.xmtp.proto.message.contents.CompositeOuterClass.internal_static_xmtp_message_contents_Composite_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.xmtp.proto.message.contents.CompositeOuterClass.Composite.class, org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Builder.class);
    }

    public interface PartOrBuilder extends
        // @@protoc_insertion_point(interface_extends:xmtp.message_contents.Composite.Part)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>.xmtp.message_contents.EncodedContent part = 1;</code>
       * @return Whether the part field is set.
       */
      boolean hasPart();
      /**
       * <code>.xmtp.message_contents.EncodedContent part = 1;</code>
       * @return The part.
       */
      org.xmtp.proto.message.contents.Content.EncodedContent getPart();
      /**
       * <code>.xmtp.message_contents.EncodedContent part = 1;</code>
       */
      org.xmtp.proto.message.contents.Content.EncodedContentOrBuilder getPartOrBuilder();

      /**
       * <code>.xmtp.message_contents.Composite composite = 2;</code>
       * @return Whether the composite field is set.
       */
      boolean hasComposite();
      /**
       * <code>.xmtp.message_contents.Composite composite = 2;</code>
       * @return The composite.
       */
      org.xmtp.proto.message.contents.CompositeOuterClass.Composite getComposite();
      /**
       * <code>.xmtp.message_contents.Composite composite = 2;</code>
       */
      org.xmtp.proto.message.contents.CompositeOuterClass.CompositeOrBuilder getCompositeOrBuilder();

      public org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part.ElementCase getElementCase();
    }
    /**
     * <pre>
     * Part represents one section of a composite message
     * </pre>
     *
     * Protobuf type {@code xmtp.message_contents.Composite.Part}
     */
    public static final class Part extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:xmtp.message_contents.Composite.Part)
        PartOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Part.newBuilder() to construct.
      private Part(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Part() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Part();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.xmtp.proto.message.contents.CompositeOuterClass.internal_static_xmtp_message_contents_Composite_Part_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.xmtp.proto.message.contents.CompositeOuterClass.internal_static_xmtp_message_contents_Composite_Part_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part.class, org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part.Builder.class);
      }

      private int elementCase_ = 0;
      private java.lang.Object element_;
      public enum ElementCase
          implements com.google.protobuf.Internal.EnumLite,
              com.google.protobuf.AbstractMessage.InternalOneOfEnum {
        PART(1),
        COMPOSITE(2),
        ELEMENT_NOT_SET(0);
        private final int value;
        private ElementCase(int value) {
          this.value = value;
        }
        /**
         * @param value The number of the enum to look for.
         * @return The enum associated with the given number.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static ElementCase valueOf(int value) {
          return forNumber(value);
        }

        public static ElementCase forNumber(int value) {
          switch (value) {
            case 1: return PART;
            case 2: return COMPOSITE;
            case 0: return ELEMENT_NOT_SET;
            default: return null;
          }
        }
        public int getNumber() {
          return this.value;
        }
      };

      public ElementCase
      getElementCase() {
        return ElementCase.forNumber(
            elementCase_);
      }

      public static final int PART_FIELD_NUMBER = 1;
      /**
       * <code>.xmtp.message_contents.EncodedContent part = 1;</code>
       * @return Whether the part field is set.
       */
      @java.lang.Override
      public boolean hasPart() {
        return elementCase_ == 1;
      }
      /**
       * <code>.xmtp.message_contents.EncodedContent part = 1;</code>
       * @return The part.
       */
      @java.lang.Override
      public org.xmtp.proto.message.contents.Content.EncodedContent getPart() {
        if (elementCase_ == 1) {
           return (org.xmtp.proto.message.contents.Content.EncodedContent) element_;
        }
        return org.xmtp.proto.message.contents.Content.EncodedContent.getDefaultInstance();
      }
      /**
       * <code>.xmtp.message_contents.EncodedContent part = 1;</code>
       */
      @java.lang.Override
      public org.xmtp.proto.message.contents.Content.EncodedContentOrBuilder getPartOrBuilder() {
        if (elementCase_ == 1) {
           return (org.xmtp.proto.message.contents.Content.EncodedContent) element_;
        }
        return org.xmtp.proto.message.contents.Content.EncodedContent.getDefaultInstance();
      }

      public static final int COMPOSITE_FIELD_NUMBER = 2;
      /**
       * <code>.xmtp.message_contents.Composite composite = 2;</code>
       * @return Whether the composite field is set.
       */
      @java.lang.Override
      public boolean hasComposite() {
        return elementCase_ == 2;
      }
      /**
       * <code>.xmtp.message_contents.Composite composite = 2;</code>
       * @return The composite.
       */
      @java.lang.Override
      public org.xmtp.proto.message.contents.CompositeOuterClass.Composite getComposite() {
        if (elementCase_ == 2) {
           return (org.xmtp.proto.message.contents.CompositeOuterClass.Composite) element_;
        }
        return org.xmtp.proto.message.contents.CompositeOuterClass.Composite.getDefaultInstance();
      }
      /**
       * <code>.xmtp.message_contents.Composite composite = 2;</code>
       */
      @java.lang.Override
      public org.xmtp.proto.message.contents.CompositeOuterClass.CompositeOrBuilder getCompositeOrBuilder() {
        if (elementCase_ == 2) {
           return (org.xmtp.proto.message.contents.CompositeOuterClass.Composite) element_;
        }
        return org.xmtp.proto.message.contents.CompositeOuterClass.Composite.getDefaultInstance();
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (elementCase_ == 1) {
          output.writeMessage(1, (org.xmtp.proto.message.contents.Content.EncodedContent) element_);
        }
        if (elementCase_ == 2) {
          output.writeMessage(2, (org.xmtp.proto.message.contents.CompositeOuterClass.Composite) element_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (elementCase_ == 1) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, (org.xmtp.proto.message.contents.Content.EncodedContent) element_);
        }
        if (elementCase_ == 2) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, (org.xmtp.proto.message.contents.CompositeOuterClass.Composite) element_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part)) {
          return super.equals(obj);
        }
        org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part other = (org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part) obj;

        if (!getElementCase().equals(other.getElementCase())) return false;
        switch (elementCase_) {
          case 1:
            if (!getPart()
                .equals(other.getPart())) return false;
            break;
          case 2:
            if (!getComposite()
                .equals(other.getComposite())) return false;
            break;
          case 0:
          default:
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        switch (elementCase_) {
          case 1:
            hash = (37 * hash) + PART_FIELD_NUMBER;
            hash = (53 * hash) + getPart().hashCode();
            break;
          case 2:
            hash = (37 * hash) + COMPOSITE_FIELD_NUMBER;
            hash = (53 * hash) + getComposite().hashCode();
            break;
          case 0:
          default:
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * Part represents one section of a composite message
       * </pre>
       *
       * Protobuf type {@code xmtp.message_contents.Composite.Part}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:xmtp.message_contents.Composite.Part)
          org.xmtp.proto.message.contents.CompositeOuterClass.Composite.PartOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.xmtp.proto.message.contents.CompositeOuterClass.internal_static_xmtp_message_contents_Composite_Part_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.xmtp.proto.message.contents.CompositeOuterClass.internal_static_xmtp_message_contents_Composite_Part_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part.class, org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part.Builder.class);
        }

        // Construct using org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          if (partBuilder_ != null) {
            partBuilder_.clear();
          }
          if (compositeBuilder_ != null) {
            compositeBuilder_.clear();
          }
          elementCase_ = 0;
          element_ = null;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.xmtp.proto.message.contents.CompositeOuterClass.internal_static_xmtp_message_contents_Composite_Part_descriptor;
        }

        @java.lang.Override
        public org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part getDefaultInstanceForType() {
          return org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part.getDefaultInstance();
        }

        @java.lang.Override
        public org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part build() {
          org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part buildPartial() {
          org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part result = new org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          buildPartialOneofs(result);
          onBuilt();
          return result;
        }

        private void buildPartial0(org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part result) {
          int from_bitField0_ = bitField0_;
        }

        private void buildPartialOneofs(org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part result) {
          result.elementCase_ = elementCase_;
          result.element_ = this.element_;
          if (elementCase_ == 1 &&
              partBuilder_ != null) {
            result.element_ = partBuilder_.build();
          }
          if (elementCase_ == 2 &&
              compositeBuilder_ != null) {
            result.element_ = compositeBuilder_.build();
          }
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part) {
            return mergeFrom((org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part other) {
          if (other == org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part.getDefaultInstance()) return this;
          switch (other.getElementCase()) {
            case PART: {
              mergePart(other.getPart());
              break;
            }
            case COMPOSITE: {
              mergeComposite(other.getComposite());
              break;
            }
            case ELEMENT_NOT_SET: {
              break;
            }
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  input.readMessage(
                      getPartFieldBuilder().getBuilder(),
                      extensionRegistry);
                  elementCase_ = 1;
                  break;
                } // case 10
                case 18: {
                  input.readMessage(
                      getCompositeFieldBuilder().getBuilder(),
                      extensionRegistry);
                  elementCase_ = 2;
                  break;
                } // case 18
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int elementCase_ = 0;
        private java.lang.Object element_;
        public ElementCase
            getElementCase() {
          return ElementCase.forNumber(
              elementCase_);
        }

        public Builder clearElement() {
          elementCase_ = 0;
          element_ = null;
          onChanged();
          return this;
        }

        private int bitField0_;

        private com.google.protobuf.SingleFieldBuilderV3<
            org.xmtp.proto.message.contents.Content.EncodedContent, org.xmtp.proto.message.contents.Content.EncodedContent.Builder, org.xmtp.proto.message.contents.Content.EncodedContentOrBuilder> partBuilder_;
        /**
         * <code>.xmtp.message_contents.EncodedContent part = 1;</code>
         * @return Whether the part field is set.
         */
        @java.lang.Override
        public boolean hasPart() {
          return elementCase_ == 1;
        }
        /**
         * <code>.xmtp.message_contents.EncodedContent part = 1;</code>
         * @return The part.
         */
        @java.lang.Override
        public org.xmtp.proto.message.contents.Content.EncodedContent getPart() {
          if (partBuilder_ == null) {
            if (elementCase_ == 1) {
              return (org.xmtp.proto.message.contents.Content.EncodedContent) element_;
            }
            return org.xmtp.proto.message.contents.Content.EncodedContent.getDefaultInstance();
          } else {
            if (elementCase_ == 1) {
              return partBuilder_.getMessage();
            }
            return org.xmtp.proto.message.contents.Content.EncodedContent.getDefaultInstance();
          }
        }
        /**
         * <code>.xmtp.message_contents.EncodedContent part = 1;</code>
         */
        public Builder setPart(org.xmtp.proto.message.contents.Content.EncodedContent value) {
          if (partBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            element_ = value;
            onChanged();
          } else {
            partBuilder_.setMessage(value);
          }
          elementCase_ = 1;
          return this;
        }
        /**
         * <code>.xmtp.message_contents.EncodedContent part = 1;</code>
         */
        public Builder setPart(
            org.xmtp.proto.message.contents.Content.EncodedContent.Builder builderForValue) {
          if (partBuilder_ == null) {
            element_ = builderForValue.build();
            onChanged();
          } else {
            partBuilder_.setMessage(builderForValue.build());
          }
          elementCase_ = 1;
          return this;
        }
        /**
         * <code>.xmtp.message_contents.EncodedContent part = 1;</code>
         */
        public Builder mergePart(org.xmtp.proto.message.contents.Content.EncodedContent value) {
          if (partBuilder_ == null) {
            if (elementCase_ == 1 &&
                element_ != org.xmtp.proto.message.contents.Content.EncodedContent.getDefaultInstance()) {
              element_ = org.xmtp.proto.message.contents.Content.EncodedContent.newBuilder((org.xmtp.proto.message.contents.Content.EncodedContent) element_)
                  .mergeFrom(value).buildPartial();
            } else {
              element_ = value;
            }
            onChanged();
          } else {
            if (elementCase_ == 1) {
              partBuilder_.mergeFrom(value);
            } else {
              partBuilder_.setMessage(value);
            }
          }
          elementCase_ = 1;
          return this;
        }
        /**
         * <code>.xmtp.message_contents.EncodedContent part = 1;</code>
         */
        public Builder clearPart() {
          if (partBuilder_ == null) {
            if (elementCase_ == 1) {
              elementCase_ = 0;
              element_ = null;
              onChanged();
            }
          } else {
            if (elementCase_ == 1) {
              elementCase_ = 0;
              element_ = null;
            }
            partBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>.xmtp.message_contents.EncodedContent part = 1;</code>
         */
        public org.xmtp.proto.message.contents.Content.EncodedContent.Builder getPartBuilder() {
          return getPartFieldBuilder().getBuilder();
        }
        /**
         * <code>.xmtp.message_contents.EncodedContent part = 1;</code>
         */
        @java.lang.Override
        public org.xmtp.proto.message.contents.Content.EncodedContentOrBuilder getPartOrBuilder() {
          if ((elementCase_ == 1) && (partBuilder_ != null)) {
            return partBuilder_.getMessageOrBuilder();
          } else {
            if (elementCase_ == 1) {
              return (org.xmtp.proto.message.contents.Content.EncodedContent) element_;
            }
            return org.xmtp.proto.message.contents.Content.EncodedContent.getDefaultInstance();
          }
        }
        /**
         * <code>.xmtp.message_contents.EncodedContent part = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            org.xmtp.proto.message.contents.Content.EncodedContent, org.xmtp.proto.message.contents.Content.EncodedContent.Builder, org.xmtp.proto.message.contents.Content.EncodedContentOrBuilder> 
            getPartFieldBuilder() {
          if (partBuilder_ == null) {
            if (!(elementCase_ == 1)) {
              element_ = org.xmtp.proto.message.contents.Content.EncodedContent.getDefaultInstance();
            }
            partBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                org.xmtp.proto.message.contents.Content.EncodedContent, org.xmtp.proto.message.contents.Content.EncodedContent.Builder, org.xmtp.proto.message.contents.Content.EncodedContentOrBuilder>(
                    (org.xmtp.proto.message.contents.Content.EncodedContent) element_,
                    getParentForChildren(),
                    isClean());
            element_ = null;
          }
          elementCase_ = 1;
          onChanged();
          return partBuilder_;
        }

        private com.google.protobuf.SingleFieldBuilderV3<
            org.xmtp.proto.message.contents.CompositeOuterClass.Composite, org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Builder, org.xmtp.proto.message.contents.CompositeOuterClass.CompositeOrBuilder> compositeBuilder_;
        /**
         * <code>.xmtp.message_contents.Composite composite = 2;</code>
         * @return Whether the composite field is set.
         */
        @java.lang.Override
        public boolean hasComposite() {
          return elementCase_ == 2;
        }
        /**
         * <code>.xmtp.message_contents.Composite composite = 2;</code>
         * @return The composite.
         */
        @java.lang.Override
        public org.xmtp.proto.message.contents.CompositeOuterClass.Composite getComposite() {
          if (compositeBuilder_ == null) {
            if (elementCase_ == 2) {
              return (org.xmtp.proto.message.contents.CompositeOuterClass.Composite) element_;
            }
            return org.xmtp.proto.message.contents.CompositeOuterClass.Composite.getDefaultInstance();
          } else {
            if (elementCase_ == 2) {
              return compositeBuilder_.getMessage();
            }
            return org.xmtp.proto.message.contents.CompositeOuterClass.Composite.getDefaultInstance();
          }
        }
        /**
         * <code>.xmtp.message_contents.Composite composite = 2;</code>
         */
        public Builder setComposite(org.xmtp.proto.message.contents.CompositeOuterClass.Composite value) {
          if (compositeBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            element_ = value;
            onChanged();
          } else {
            compositeBuilder_.setMessage(value);
          }
          elementCase_ = 2;
          return this;
        }
        /**
         * <code>.xmtp.message_contents.Composite composite = 2;</code>
         */
        public Builder setComposite(
            org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Builder builderForValue) {
          if (compositeBuilder_ == null) {
            element_ = builderForValue.build();
            onChanged();
          } else {
            compositeBuilder_.setMessage(builderForValue.build());
          }
          elementCase_ = 2;
          return this;
        }
        /**
         * <code>.xmtp.message_contents.Composite composite = 2;</code>
         */
        public Builder mergeComposite(org.xmtp.proto.message.contents.CompositeOuterClass.Composite value) {
          if (compositeBuilder_ == null) {
            if (elementCase_ == 2 &&
                element_ != org.xmtp.proto.message.contents.CompositeOuterClass.Composite.getDefaultInstance()) {
              element_ = org.xmtp.proto.message.contents.CompositeOuterClass.Composite.newBuilder((org.xmtp.proto.message.contents.CompositeOuterClass.Composite) element_)
                  .mergeFrom(value).buildPartial();
            } else {
              element_ = value;
            }
            onChanged();
          } else {
            if (elementCase_ == 2) {
              compositeBuilder_.mergeFrom(value);
            } else {
              compositeBuilder_.setMessage(value);
            }
          }
          elementCase_ = 2;
          return this;
        }
        /**
         * <code>.xmtp.message_contents.Composite composite = 2;</code>
         */
        public Builder clearComposite() {
          if (compositeBuilder_ == null) {
            if (elementCase_ == 2) {
              elementCase_ = 0;
              element_ = null;
              onChanged();
            }
          } else {
            if (elementCase_ == 2) {
              elementCase_ = 0;
              element_ = null;
            }
            compositeBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>.xmtp.message_contents.Composite composite = 2;</code>
         */
        public org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Builder getCompositeBuilder() {
          return getCompositeFieldBuilder().getBuilder();
        }
        /**
         * <code>.xmtp.message_contents.Composite composite = 2;</code>
         */
        @java.lang.Override
        public org.xmtp.proto.message.contents.CompositeOuterClass.CompositeOrBuilder getCompositeOrBuilder() {
          if ((elementCase_ == 2) && (compositeBuilder_ != null)) {
            return compositeBuilder_.getMessageOrBuilder();
          } else {
            if (elementCase_ == 2) {
              return (org.xmtp.proto.message.contents.CompositeOuterClass.Composite) element_;
            }
            return org.xmtp.proto.message.contents.CompositeOuterClass.Composite.getDefaultInstance();
          }
        }
        /**
         * <code>.xmtp.message_contents.Composite composite = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            org.xmtp.proto.message.contents.CompositeOuterClass.Composite, org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Builder, org.xmtp.proto.message.contents.CompositeOuterClass.CompositeOrBuilder> 
            getCompositeFieldBuilder() {
          if (compositeBuilder_ == null) {
            if (!(elementCase_ == 2)) {
              element_ = org.xmtp.proto.message.contents.CompositeOuterClass.Composite.getDefaultInstance();
            }
            compositeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                org.xmtp.proto.message.contents.CompositeOuterClass.Composite, org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Builder, org.xmtp.proto.message.contents.CompositeOuterClass.CompositeOrBuilder>(
                    (org.xmtp.proto.message.contents.CompositeOuterClass.Composite) element_,
                    getParentForChildren(),
                    isClean());
            element_ = null;
          }
          elementCase_ = 2;
          onChanged();
          return compositeBuilder_;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:xmtp.message_contents.Composite.Part)
      }

      // @@protoc_insertion_point(class_scope:xmtp.message_contents.Composite.Part)
      private static final org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part();
      }

      public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Part>
          PARSER = new com.google.protobuf.AbstractParser<Part>() {
        @java.lang.Override
        public Part parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<Part> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Part> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int PARTS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part> parts_;
    /**
     * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part> getPartsList() {
      return parts_;
    }
    /**
     * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.xmtp.proto.message.contents.CompositeOuterClass.Composite.PartOrBuilder> 
        getPartsOrBuilderList() {
      return parts_;
    }
    /**
     * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
     */
    @java.lang.Override
    public int getPartsCount() {
      return parts_.size();
    }
    /**
     * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
     */
    @java.lang.Override
    public org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part getParts(int index) {
      return parts_.get(index);
    }
    /**
     * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
     */
    @java.lang.Override
    public org.xmtp.proto.message.contents.CompositeOuterClass.Composite.PartOrBuilder getPartsOrBuilder(
        int index) {
      return parts_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < parts_.size(); i++) {
        output.writeMessage(1, parts_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < parts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, parts_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.xmtp.proto.message.contents.CompositeOuterClass.Composite)) {
        return super.equals(obj);
      }
      org.xmtp.proto.message.contents.CompositeOuterClass.Composite other = (org.xmtp.proto.message.contents.CompositeOuterClass.Composite) obj;

      if (!getPartsList()
          .equals(other.getPartsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPartsCount() > 0) {
        hash = (37 * hash) + PARTS_FIELD_NUMBER;
        hash = (53 * hash) + getPartsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.xmtp.proto.message.contents.CompositeOuterClass.Composite prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Composite is used to implement xmtp.org/composite content type
     * </pre>
     *
     * Protobuf type {@code xmtp.message_contents.Composite}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:xmtp.message_contents.Composite)
        org.xmtp.proto.message.contents.CompositeOuterClass.CompositeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.xmtp.proto.message.contents.CompositeOuterClass.internal_static_xmtp_message_contents_Composite_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.xmtp.proto.message.contents.CompositeOuterClass.internal_static_xmtp_message_contents_Composite_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.xmtp.proto.message.contents.CompositeOuterClass.Composite.class, org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Builder.class);
      }

      // Construct using org.xmtp.proto.message.contents.CompositeOuterClass.Composite.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (partsBuilder_ == null) {
          parts_ = java.util.Collections.emptyList();
        } else {
          parts_ = null;
          partsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.xmtp.proto.message.contents.CompositeOuterClass.internal_static_xmtp_message_contents_Composite_descriptor;
      }

      @java.lang.Override
      public org.xmtp.proto.message.contents.CompositeOuterClass.Composite getDefaultInstanceForType() {
        return org.xmtp.proto.message.contents.CompositeOuterClass.Composite.getDefaultInstance();
      }

      @java.lang.Override
      public org.xmtp.proto.message.contents.CompositeOuterClass.Composite build() {
        org.xmtp.proto.message.contents.CompositeOuterClass.Composite result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.xmtp.proto.message.contents.CompositeOuterClass.Composite buildPartial() {
        org.xmtp.proto.message.contents.CompositeOuterClass.Composite result = new org.xmtp.proto.message.contents.CompositeOuterClass.Composite(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.xmtp.proto.message.contents.CompositeOuterClass.Composite result) {
        if (partsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            parts_ = java.util.Collections.unmodifiableList(parts_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.parts_ = parts_;
        } else {
          result.parts_ = partsBuilder_.build();
        }
      }

      private void buildPartial0(org.xmtp.proto.message.contents.CompositeOuterClass.Composite result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.xmtp.proto.message.contents.CompositeOuterClass.Composite) {
          return mergeFrom((org.xmtp.proto.message.contents.CompositeOuterClass.Composite)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.xmtp.proto.message.contents.CompositeOuterClass.Composite other) {
        if (other == org.xmtp.proto.message.contents.CompositeOuterClass.Composite.getDefaultInstance()) return this;
        if (partsBuilder_ == null) {
          if (!other.parts_.isEmpty()) {
            if (parts_.isEmpty()) {
              parts_ = other.parts_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePartsIsMutable();
              parts_.addAll(other.parts_);
            }
            onChanged();
          }
        } else {
          if (!other.parts_.isEmpty()) {
            if (partsBuilder_.isEmpty()) {
              partsBuilder_.dispose();
              partsBuilder_ = null;
              parts_ = other.parts_;
              bitField0_ = (bitField0_ & ~0x00000001);
              partsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPartsFieldBuilder() : null;
            } else {
              partsBuilder_.addAllMessages(other.parts_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part m =
                    input.readMessage(
                        org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part.parser(),
                        extensionRegistry);
                if (partsBuilder_ == null) {
                  ensurePartsIsMutable();
                  parts_.add(m);
                } else {
                  partsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part> parts_ =
        java.util.Collections.emptyList();
      private void ensurePartsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          parts_ = new java.util.ArrayList<org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part>(parts_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part, org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part.Builder, org.xmtp.proto.message.contents.CompositeOuterClass.Composite.PartOrBuilder> partsBuilder_;

      /**
       * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
       */
      public java.util.List<org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part> getPartsList() {
        if (partsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(parts_);
        } else {
          return partsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
       */
      public int getPartsCount() {
        if (partsBuilder_ == null) {
          return parts_.size();
        } else {
          return partsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
       */
      public org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part getParts(int index) {
        if (partsBuilder_ == null) {
          return parts_.get(index);
        } else {
          return partsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
       */
      public Builder setParts(
          int index, org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part value) {
        if (partsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePartsIsMutable();
          parts_.set(index, value);
          onChanged();
        } else {
          partsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
       */
      public Builder setParts(
          int index, org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part.Builder builderForValue) {
        if (partsBuilder_ == null) {
          ensurePartsIsMutable();
          parts_.set(index, builderForValue.build());
          onChanged();
        } else {
          partsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
       */
      public Builder addParts(org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part value) {
        if (partsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePartsIsMutable();
          parts_.add(value);
          onChanged();
        } else {
          partsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
       */
      public Builder addParts(
          int index, org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part value) {
        if (partsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePartsIsMutable();
          parts_.add(index, value);
          onChanged();
        } else {
          partsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
       */
      public Builder addParts(
          org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part.Builder builderForValue) {
        if (partsBuilder_ == null) {
          ensurePartsIsMutable();
          parts_.add(builderForValue.build());
          onChanged();
        } else {
          partsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
       */
      public Builder addParts(
          int index, org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part.Builder builderForValue) {
        if (partsBuilder_ == null) {
          ensurePartsIsMutable();
          parts_.add(index, builderForValue.build());
          onChanged();
        } else {
          partsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
       */
      public Builder addAllParts(
          java.lang.Iterable<? extends org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part> values) {
        if (partsBuilder_ == null) {
          ensurePartsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, parts_);
          onChanged();
        } else {
          partsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
       */
      public Builder clearParts() {
        if (partsBuilder_ == null) {
          parts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          partsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
       */
      public Builder removeParts(int index) {
        if (partsBuilder_ == null) {
          ensurePartsIsMutable();
          parts_.remove(index);
          onChanged();
        } else {
          partsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
       */
      public org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part.Builder getPartsBuilder(
          int index) {
        return getPartsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
       */
      public org.xmtp.proto.message.contents.CompositeOuterClass.Composite.PartOrBuilder getPartsOrBuilder(
          int index) {
        if (partsBuilder_ == null) {
          return parts_.get(index);  } else {
          return partsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
       */
      public java.util.List<? extends org.xmtp.proto.message.contents.CompositeOuterClass.Composite.PartOrBuilder> 
           getPartsOrBuilderList() {
        if (partsBuilder_ != null) {
          return partsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(parts_);
        }
      }
      /**
       * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
       */
      public org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part.Builder addPartsBuilder() {
        return getPartsFieldBuilder().addBuilder(
            org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part.getDefaultInstance());
      }
      /**
       * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
       */
      public org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part.Builder addPartsBuilder(
          int index) {
        return getPartsFieldBuilder().addBuilder(
            index, org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part.getDefaultInstance());
      }
      /**
       * <code>repeated .xmtp.message_contents.Composite.Part parts = 1;</code>
       */
      public java.util.List<org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part.Builder> 
           getPartsBuilderList() {
        return getPartsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part, org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part.Builder, org.xmtp.proto.message.contents.CompositeOuterClass.Composite.PartOrBuilder> 
          getPartsFieldBuilder() {
        if (partsBuilder_ == null) {
          partsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part, org.xmtp.proto.message.contents.CompositeOuterClass.Composite.Part.Builder, org.xmtp.proto.message.contents.CompositeOuterClass.Composite.PartOrBuilder>(
                  parts_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          parts_ = null;
        }
        return partsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:xmtp.message_contents.Composite)
    }

    // @@protoc_insertion_point(class_scope:xmtp.message_contents.Composite)
    private static final org.xmtp.proto.message.contents.CompositeOuterClass.Composite DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.xmtp.proto.message.contents.CompositeOuterClass.Composite();
    }

    public static org.xmtp.proto.message.contents.CompositeOuterClass.Composite getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Composite>
        PARSER = new com.google.protobuf.AbstractParser<Composite>() {
      @java.lang.Override
      public Composite parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Composite> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Composite> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.xmtp.proto.message.contents.CompositeOuterClass.Composite getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xmtp_message_contents_Composite_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xmtp_message_contents_Composite_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xmtp_message_contents_Composite_Part_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xmtp_message_contents_Composite_Part_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n message_contents/composite.proto\022\025xmtp" +
      ".message_contents\032\036message_contents/cont" +
      "ent.proto\"\302\001\n\tComposite\0224\n\005parts\030\001 \003(\0132%" +
      ".xmtp.message_contents.Composite.Part\032\177\n" +
      "\004Part\0225\n\004part\030\001 \001(\0132%.xmtp.message_conte" +
      "nts.EncodedContentH\000\0225\n\tcomposite\030\002 \001(\0132" +
      " .xmtp.message_contents.CompositeH\000B\t\n\007e" +
      "lementBO\n\037org.xmtp.proto.message.content" +
      "sZ,github.com/xmtp/proto/v3/go/message_c" +
      "ontentsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.xmtp.proto.message.contents.Content.getDescriptor(),
        });
    internal_static_xmtp_message_contents_Composite_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xmtp_message_contents_Composite_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xmtp_message_contents_Composite_descriptor,
        new java.lang.String[] { "Parts", });
    internal_static_xmtp_message_contents_Composite_Part_descriptor =
      internal_static_xmtp_message_contents_Composite_descriptor.getNestedTypes().get(0);
    internal_static_xmtp_message_contents_Composite_Part_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xmtp_message_contents_Composite_Part_descriptor,
        new java.lang.String[] { "Part", "Composite", "Element", });
    org.xmtp.proto.message.contents.Content.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
