//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_contents/invitation.proto

package org.xmtp.proto.message.contents;

@kotlin.jvm.JvmName("-initializesealedInvitation")
public inline fun sealedInvitation(block: org.xmtp.proto.message.contents.SealedInvitationKt.Dsl.() -> kotlin.Unit): org.xmtp.proto.message.contents.Invitation.SealedInvitation =
  org.xmtp.proto.message.contents.SealedInvitationKt.Dsl._create(org.xmtp.proto.message.contents.Invitation.SealedInvitation.newBuilder()).apply { block() }._build()
public object SealedInvitationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: org.xmtp.proto.message.contents.Invitation.SealedInvitation.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: org.xmtp.proto.message.contents.Invitation.SealedInvitation.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): org.xmtp.proto.message.contents.Invitation.SealedInvitation = _builder.build()

    /**
     * <code>.xmtp.message_contents.SealedInvitationV1 v1 = 1;</code>
     */
    public var v1: org.xmtp.proto.message.contents.Invitation.SealedInvitationV1
      @JvmName("getV1")
      get() = _builder.getV1()
      @JvmName("setV1")
      set(value) {
        _builder.setV1(value)
      }
    /**
     * <code>.xmtp.message_contents.SealedInvitationV1 v1 = 1;</code>
     */
    public fun clearV1() {
      _builder.clearV1()
    }
    /**
     * <code>.xmtp.message_contents.SealedInvitationV1 v1 = 1;</code>
     * @return Whether the v1 field is set.
     */
    public fun hasV1(): kotlin.Boolean {
      return _builder.hasV1()
    }
    public val versionCase: org.xmtp.proto.message.contents.Invitation.SealedInvitation.VersionCase
      @JvmName("getVersionCase")
      get() = _builder.getVersionCase()

    public fun clearVersion() {
      _builder.clearVersion()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun org.xmtp.proto.message.contents.Invitation.SealedInvitation.copy(block: org.xmtp.proto.message.contents.SealedInvitationKt.Dsl.() -> kotlin.Unit): org.xmtp.proto.message.contents.Invitation.SealedInvitation =
  org.xmtp.proto.message.contents.SealedInvitationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val org.xmtp.proto.message.contents.Invitation.SealedInvitationOrBuilder.v1OrNull: org.xmtp.proto.message.contents.Invitation.SealedInvitationV1?
  get() = if (hasV1()) getV1() else null

