#!/usr/bin/env bash
set -e

(
  cd dev/kotlin/protoc
  docker build --platform linux/x86_64 -t xmtp/protoc-kotlin . 
)

rm -rf ./kotlin/src/main/kotlin
mkdir -p ./kotlin/src/main/kotlin

docker run --platform linux/x86_64 --rm -i -v${PWD}:/code xmtp/protoc-kotlin \
    -I=./proto \
    --proto_path=./proto \
    --plugin=protoc-gen-grpckt=dev/kotlin/protoc/protoc-gen-grpc-kotlin.sh \
    --grpckt_out=./kotlin/src/main/kotlin \
  message_api/v1/message_api.proto

docker run --platform linux/x86_64 --rm -i -v${PWD}:/code xmtp/protoc-kotlin \
  -I=./proto \
  --proto_path=./proto \
  --experimental_allow_proto3_optional \
  --java_out=./kotlin/src/main/kotlin \
  --kotlin_out=./kotlin/src/main/kotlin \
  message_api/v1/message_api.proto \
  message_api/v1/authn.proto \
  message_contents/composite.proto \
  message_contents/signature.proto \
  message_contents/ciphertext.proto \
  message_contents/public_key.proto \
  message_contents/contact.proto \
  message_contents/invitation.proto \
  message_contents/private_key.proto \
  message_contents/message.proto \
  message_contents/content.proto