#!/usr/bin/env bash
set -e

(
  cd dev/kotlin/protoc
  docker build --platform linux/x86_64 -t xmtp/protoc-kotlin .
)

rm -rf ./kotlin/lib/src/main/kotlin
mkdir -p ./kotlin/lib/src/main/kotlin

# Need Plugins for both Java and Kotlin see: https://developers.google.com/protocol-buffers/docs/reference/kotlin-generated
docker run --platform linux/x86_64 --rm -i -v${PWD}:/code xmtp/protoc-kotlin \
    -I=./proto \
    --proto_path=./proto \
    --plugin=protoc-gen-grpckt=dev/kotlin/protoc/protoc-gen-grpc-kotlin.sh \
    --plugin=protoc-gen-java_rpc=../../build/binaries/java_pluginExecutable/protoc-gen-grpc-java \
    --grpc-java_out=lite:./kotlin/lib/src/main/kotlin \
    --grpckt_out=lite:./kotlin/lib/src/main/kotlin \
  mls/api/v1/mls.proto

docker run --platform linux/x86_64 --rm -i -v${PWD}:/code xmtp/protoc-kotlin \
  -I=./proto \
  --proto_path=./proto \
  --experimental_allow_proto3_optional \
  --java_out=lite:./kotlin/lib/src/main/kotlin \
  --kotlin_out=lite:./kotlin/lib/src/main/kotlin \
  keystore_api/v1/keystore.proto \
  message_contents/public_key.proto \
  message_contents/private_key.proto \
  message_contents/ciphertext.proto \
  message_contents/signature.proto \
  mls/api/v1/mls.proto \
  mls/database/intents.proto \
  mls/message_contents/group_metadata.proto \
  mls/message_contents/group_mutable_metadata.proto \
  mls/message_contents/content.proto \
  mls/message_contents/transcript_messages.proto
