#!/usr/bin/env bash
set -e

(
  cd dev/kotlin/protoc
  docker build -t xmtp/protoc-kotlin .
)

rm -f ./kotlin/**/*.pb.kotlin || true

docker run --rm -i -v${PWD}:/code xmtp/protoc-kotlin \
    -I=./proto \
    --proto_path=./proto \
    --plugin=protoc-gen-grpckt=compiler/build/install/compiler/bin/compiler \
    --grpckt_out=./kotlin\
    --java_out=./kotlin \
    --kotlin_out=./kotlin \
  message_api/v1/message_api.proto


docker run --rm -i -v${PWD}:/code xmtp/protoc-kotlin \
  -I=./proto \
  --proto_path=./proto \
  --experimental_allow_proto3_optional \
  --plugin=protoc-gen-grpckt=compiler/build/install/compiler/bin/compiler \
  --grpckt_out=./kotlin\
  --java_out=./kotlin \
  --kotlin_out=./kotlin \
  message_api/v1/message_api.proto \
  message_api/v1/authn.proto \
  message_contents/composite.proto \
  message_contents/signature.proto \
  message_contents/ciphertext.proto \
  message_contents/public_key.proto \
  message_contents/contact.proto \
  message_contents/invitation.proto \
  message_contents/private_key.proto \
  message_contents/message.proto \
  message_contents/content.proto