//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_api/v1/message_api.proto

package org.xmtp.proto.message.api.v1;

@kotlin.jvm.JvmName("-initializesubscribeAllRequest")
public inline fun subscribeAllRequest(block: org.xmtp.proto.message.api.v1.SubscribeAllRequestKt.Dsl.() -> kotlin.Unit): org.xmtp.proto.message.api.v1.MessageApiOuterClass.SubscribeAllRequest =
  org.xmtp.proto.message.api.v1.SubscribeAllRequestKt.Dsl._create(org.xmtp.proto.message.api.v1.MessageApiOuterClass.SubscribeAllRequest.newBuilder()).apply { block() }._build()
public object SubscribeAllRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: org.xmtp.proto.message.api.v1.MessageApiOuterClass.SubscribeAllRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: org.xmtp.proto.message.api.v1.MessageApiOuterClass.SubscribeAllRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): org.xmtp.proto.message.api.v1.MessageApiOuterClass.SubscribeAllRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun org.xmtp.proto.message.api.v1.MessageApiOuterClass.SubscribeAllRequest.copy(block: org.xmtp.proto.message.api.v1.SubscribeAllRequestKt.Dsl.() -> kotlin.Unit): org.xmtp.proto.message.api.v1.MessageApiOuterClass.SubscribeAllRequest =
  org.xmtp.proto.message.api.v1.SubscribeAllRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

