//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_contents/ciphertext.proto

package org.xmtp.proto.message.contents;

@kotlin.jvm.JvmName("-initializeciphertext")
public inline fun ciphertext(block: org.xmtp.proto.message.contents.CiphertextKt.Dsl.() -> kotlin.Unit): org.xmtp.proto.message.contents.CiphertextOuterClass.Ciphertext =
  org.xmtp.proto.message.contents.CiphertextKt.Dsl._create(org.xmtp.proto.message.contents.CiphertextOuterClass.Ciphertext.newBuilder()).apply { block() }._build()
public object CiphertextKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: org.xmtp.proto.message.contents.CiphertextOuterClass.Ciphertext.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: org.xmtp.proto.message.contents.CiphertextOuterClass.Ciphertext.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): org.xmtp.proto.message.contents.CiphertextOuterClass.Ciphertext = _builder.build()

    /**
     * <code>.xmtp.message_contents.Ciphertext.Aes256gcmHkdfsha256 aes256_gcm_hkdf_sha256 = 1;</code>
     */
    public var aes256GcmHkdfSha256: org.xmtp.proto.message.contents.CiphertextOuterClass.Ciphertext.Aes256gcmHkdfsha256
      @JvmName("getAes256GcmHkdfSha256")
      get() = _builder.getAes256GcmHkdfSha256()
      @JvmName("setAes256GcmHkdfSha256")
      set(value) {
        _builder.setAes256GcmHkdfSha256(value)
      }
    /**
     * <code>.xmtp.message_contents.Ciphertext.Aes256gcmHkdfsha256 aes256_gcm_hkdf_sha256 = 1;</code>
     */
    public fun clearAes256GcmHkdfSha256() {
      _builder.clearAes256GcmHkdfSha256()
    }
    /**
     * <code>.xmtp.message_contents.Ciphertext.Aes256gcmHkdfsha256 aes256_gcm_hkdf_sha256 = 1;</code>
     * @return Whether the aes256GcmHkdfSha256 field is set.
     */
    public fun hasAes256GcmHkdfSha256(): kotlin.Boolean {
      return _builder.hasAes256GcmHkdfSha256()
    }
    public val unionCase: org.xmtp.proto.message.contents.CiphertextOuterClass.Ciphertext.UnionCase
      @JvmName("getUnionCase")
      get() = _builder.getUnionCase()

    public fun clearUnion() {
      _builder.clearUnion()
    }
  }
  @kotlin.jvm.JvmName("-initializeaes256gcmHkdfsha256")
  public inline fun aes256gcmHkdfsha256(block: org.xmtp.proto.message.contents.CiphertextKt.Aes256gcmHkdfsha256Kt.Dsl.() -> kotlin.Unit): org.xmtp.proto.message.contents.CiphertextOuterClass.Ciphertext.Aes256gcmHkdfsha256 =
    org.xmtp.proto.message.contents.CiphertextKt.Aes256gcmHkdfsha256Kt.Dsl._create(org.xmtp.proto.message.contents.CiphertextOuterClass.Ciphertext.Aes256gcmHkdfsha256.newBuilder()).apply { block() }._build()
  public object Aes256gcmHkdfsha256Kt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: org.xmtp.proto.message.contents.CiphertextOuterClass.Ciphertext.Aes256gcmHkdfsha256.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: org.xmtp.proto.message.contents.CiphertextOuterClass.Ciphertext.Aes256gcmHkdfsha256.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): org.xmtp.proto.message.contents.CiphertextOuterClass.Ciphertext.Aes256gcmHkdfsha256 = _builder.build()

      /**
       * <pre>
       * 32 bytes
       * </pre>
       *
       * <code>bytes hkdf_salt = 1;</code>
       */
      public var hkdfSalt: com.google.protobuf.ByteString
        @JvmName("getHkdfSalt")
        get() = _builder.getHkdfSalt()
        @JvmName("setHkdfSalt")
        set(value) {
          _builder.setHkdfSalt(value)
        }
      /**
       * <pre>
       * 32 bytes
       * </pre>
       *
       * <code>bytes hkdf_salt = 1;</code>
       */
      public fun clearHkdfSalt() {
        _builder.clearHkdfSalt()
      }

      /**
       * <pre>
       * 12 bytes
       * </pre>
       *
       * <code>bytes gcm_nonce = 2;</code>
       */
      public var gcmNonce: com.google.protobuf.ByteString
        @JvmName("getGcmNonce")
        get() = _builder.getGcmNonce()
        @JvmName("setGcmNonce")
        set(value) {
          _builder.setGcmNonce(value)
        }
      /**
       * <pre>
       * 12 bytes
       * </pre>
       *
       * <code>bytes gcm_nonce = 2;</code>
       */
      public fun clearGcmNonce() {
        _builder.clearGcmNonce()
      }

      /**
       * <pre>
       * encrypted payload
       * </pre>
       *
       * <code>bytes payload = 3;</code>
       */
      public var payload: com.google.protobuf.ByteString
        @JvmName("getPayload")
        get() = _builder.getPayload()
        @JvmName("setPayload")
        set(value) {
          _builder.setPayload(value)
        }
      /**
       * <pre>
       * encrypted payload
       * </pre>
       *
       * <code>bytes payload = 3;</code>
       */
      public fun clearPayload() {
        _builder.clearPayload()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun org.xmtp.proto.message.contents.CiphertextOuterClass.Ciphertext.copy(block: org.xmtp.proto.message.contents.CiphertextKt.Dsl.() -> kotlin.Unit): org.xmtp.proto.message.contents.CiphertextOuterClass.Ciphertext =
  org.xmtp.proto.message.contents.CiphertextKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun org.xmtp.proto.message.contents.CiphertextOuterClass.Ciphertext.Aes256gcmHkdfsha256.copy(block: org.xmtp.proto.message.contents.CiphertextKt.Aes256gcmHkdfsha256Kt.Dsl.() -> kotlin.Unit): org.xmtp.proto.message.contents.CiphertextOuterClass.Ciphertext.Aes256gcmHkdfsha256 =
  org.xmtp.proto.message.contents.CiphertextKt.Aes256gcmHkdfsha256Kt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val org.xmtp.proto.message.contents.CiphertextOuterClass.CiphertextOrBuilder.aes256GcmHkdfSha256OrNull: org.xmtp.proto.message.contents.CiphertextOuterClass.Ciphertext.Aes256gcmHkdfsha256?
  get() = if (hasAes256GcmHkdfSha256()) getAes256GcmHkdfSha256() else null

