//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_contents/private_key.proto

package org.xmtp.proto.message.contents;

@kotlin.jvm.JvmName("-initializesignedPrivateKey")
public inline fun signedPrivateKey(block: org.xmtp.proto.message.contents.SignedPrivateKeyKt.Dsl.() -> kotlin.Unit): org.xmtp.proto.message.contents.PrivateKeyOuterClass.SignedPrivateKey =
  org.xmtp.proto.message.contents.SignedPrivateKeyKt.Dsl._create(org.xmtp.proto.message.contents.PrivateKeyOuterClass.SignedPrivateKey.newBuilder()).apply { block() }._build()
public object SignedPrivateKeyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: org.xmtp.proto.message.contents.PrivateKeyOuterClass.SignedPrivateKey.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: org.xmtp.proto.message.contents.PrivateKeyOuterClass.SignedPrivateKey.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): org.xmtp.proto.message.contents.PrivateKeyOuterClass.SignedPrivateKey = _builder.build()

    /**
     * <pre>
     * time the key was created
     * </pre>
     *
     * <code>uint64 created_ns = 1;</code>
     */
    public var createdNs: kotlin.Long
      @JvmName("getCreatedNs")
      get() = _builder.getCreatedNs()
      @JvmName("setCreatedNs")
      set(value) {
        _builder.setCreatedNs(value)
      }
    /**
     * <pre>
     * time the key was created
     * </pre>
     *
     * <code>uint64 created_ns = 1;</code>
     */
    public fun clearCreatedNs() {
      _builder.clearCreatedNs()
    }

    /**
     * <code>.xmtp.message_contents.SignedPrivateKey.Secp256k1 secp256k1 = 2;</code>
     */
    public var secp256K1: org.xmtp.proto.message.contents.PrivateKeyOuterClass.SignedPrivateKey.Secp256k1
      @JvmName("getSecp256K1")
      get() = _builder.getSecp256K1()
      @JvmName("setSecp256K1")
      set(value) {
        _builder.setSecp256K1(value)
      }
    /**
     * <code>.xmtp.message_contents.SignedPrivateKey.Secp256k1 secp256k1 = 2;</code>
     */
    public fun clearSecp256K1() {
      _builder.clearSecp256K1()
    }
    /**
     * <code>.xmtp.message_contents.SignedPrivateKey.Secp256k1 secp256k1 = 2;</code>
     * @return Whether the secp256k1 field is set.
     */
    public fun hasSecp256K1(): kotlin.Boolean {
      return _builder.hasSecp256K1()
    }

    /**
     * <pre>
     * public key for this private key
     * </pre>
     *
     * <code>.xmtp.message_contents.SignedPublicKey public_key = 3;</code>
     */
    public var publicKey: org.xmtp.proto.message.contents.PublicKeyOuterClass.SignedPublicKey
      @JvmName("getPublicKey")
      get() = _builder.getPublicKey()
      @JvmName("setPublicKey")
      set(value) {
        _builder.setPublicKey(value)
      }
    /**
     * <pre>
     * public key for this private key
     * </pre>
     *
     * <code>.xmtp.message_contents.SignedPublicKey public_key = 3;</code>
     */
    public fun clearPublicKey() {
      _builder.clearPublicKey()
    }
    /**
     * <pre>
     * public key for this private key
     * </pre>
     *
     * <code>.xmtp.message_contents.SignedPublicKey public_key = 3;</code>
     * @return Whether the publicKey field is set.
     */
    public fun hasPublicKey(): kotlin.Boolean {
      return _builder.hasPublicKey()
    }
    public val unionCase: org.xmtp.proto.message.contents.PrivateKeyOuterClass.SignedPrivateKey.UnionCase
      @JvmName("getUnionCase")
      get() = _builder.getUnionCase()

    public fun clearUnion() {
      _builder.clearUnion()
    }
  }
  @kotlin.jvm.JvmName("-initializesecp256k1")
  public inline fun secp256k1(block: org.xmtp.proto.message.contents.SignedPrivateKeyKt.Secp256k1Kt.Dsl.() -> kotlin.Unit): org.xmtp.proto.message.contents.PrivateKeyOuterClass.SignedPrivateKey.Secp256k1 =
    org.xmtp.proto.message.contents.SignedPrivateKeyKt.Secp256k1Kt.Dsl._create(org.xmtp.proto.message.contents.PrivateKeyOuterClass.SignedPrivateKey.Secp256k1.newBuilder()).apply { block() }._build()
  public object Secp256k1Kt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: org.xmtp.proto.message.contents.PrivateKeyOuterClass.SignedPrivateKey.Secp256k1.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: org.xmtp.proto.message.contents.PrivateKeyOuterClass.SignedPrivateKey.Secp256k1.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): org.xmtp.proto.message.contents.PrivateKeyOuterClass.SignedPrivateKey.Secp256k1 = _builder.build()

      /**
       * <pre>
       * D big-endian, 32 bytes
       * </pre>
       *
       * <code>bytes bytes = 1;</code>
       */
      public var bytes: com.google.protobuf.ByteString
        @JvmName("getBytes")
        get() = _builder.getBytes()
        @JvmName("setBytes")
        set(value) {
          _builder.setBytes(value)
        }
      /**
       * <pre>
       * D big-endian, 32 bytes
       * </pre>
       *
       * <code>bytes bytes = 1;</code>
       */
      public fun clearBytes() {
        _builder.clearBytes()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun org.xmtp.proto.message.contents.PrivateKeyOuterClass.SignedPrivateKey.copy(block: org.xmtp.proto.message.contents.SignedPrivateKeyKt.Dsl.() -> kotlin.Unit): org.xmtp.proto.message.contents.PrivateKeyOuterClass.SignedPrivateKey =
  org.xmtp.proto.message.contents.SignedPrivateKeyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun org.xmtp.proto.message.contents.PrivateKeyOuterClass.SignedPrivateKey.Secp256k1.copy(block: org.xmtp.proto.message.contents.SignedPrivateKeyKt.Secp256k1Kt.Dsl.() -> kotlin.Unit): org.xmtp.proto.message.contents.PrivateKeyOuterClass.SignedPrivateKey.Secp256k1 =
  org.xmtp.proto.message.contents.SignedPrivateKeyKt.Secp256k1Kt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val org.xmtp.proto.message.contents.PrivateKeyOuterClass.SignedPrivateKeyOrBuilder.secp256K1OrNull: org.xmtp.proto.message.contents.PrivateKeyOuterClass.SignedPrivateKey.Secp256k1?
  get() = if (hasSecp256K1()) getSecp256K1() else null

public val org.xmtp.proto.message.contents.PrivateKeyOuterClass.SignedPrivateKeyOrBuilder.publicKeyOrNull: org.xmtp.proto.message.contents.PublicKeyOuterClass.SignedPublicKey?
  get() = if (hasPublicKey()) getPublicKey() else null

