#!/usr/bin/env bash
set -e

(
  cd dev/java/protoc
  docker build --platform linux/x86_64 -t xmtp/protoc-java . 
)

rm -rf ./java
mkdir -p ./java

docker run --platform linux/x86_64 --rm -i -v${PWD}:/code xmtp/protoc-java \
    -I=./proto \
    --proto_path=./proto \
    --plugin=protoc-gen-java_rpc=../../build/binaries/java_pluginExecutable/protoc-gen-grpc-java \
    --grpc-java_out=./java \
    --java_out=./java \
  message_api/v1/message_api.proto

docker run --platform linux/x86_64 --rm -i -v${PWD}:/code xmtp/protoc-java \
  -I=./proto \
  --proto_path=./proto \
  --experimental_allow_proto3_optional \
  --java_out=./java \
  message_api/v1/message_api.proto \
  message_api/v1/authn.proto \
  message_contents/composite.proto \
  message_contents/signature.proto \
  message_contents/ciphertext.proto \
  message_contents/public_key.proto \
  message_contents/contact.proto \
  message_contents/invitation.proto \
  message_contents/private_key.proto \
  message_contents/message.proto \
  message_contents/content.proto