#!/usr/bin/env bash
set -e

(
  cd dev/swift/protoc
  docker build -t xmtp/protoc-swift .
)

rm -f ./swift/**/*.pb.swift || true

docker run --rm -i -v${PWD}:/code xmtp/protoc-swift \
  --experimental_allow_proto3_optional \
  --swift_out=./swift \
  --swift_opt=Visibility=Public \
  --proto_path=./proto \
  message_api/v1/message_api.proto \
  message_api/v1/authn.proto \
  message_contents/composite.proto \
  message_contents/signature.proto \
  message_contents/ciphertext.proto \
  message_contents/public_key.proto \
  message_contents/contact.proto \
  message_contents/invitation.proto \
  message_contents/private_key.proto \
  message_contents/xmtp_envelope.proto
